// Seed data parsed from bottle_bible_interactive-2.html
// property_id is injected at seed time from VITE_PROPERTY_ID

export const seedWines = [
  // ===== LOIRE VALLEY =====
  {
    name: "Muscadet Sèvre & Maine sur Lie 'Garance'",
    producer: 'Pierre Luneau-Papin',
    vintage: 2024,
    region: 'Loire Valley',
    country: 'France',
    grape: 'Muscadet',
    type: 'white',
    body: 'light',
    bottle_price: 47,
    glass_price: 13.25,
    carafe_price: 25.50,
    by_the_glass: true,
    coravin: false,
    tasting_notes: 'Light, crisp, mineral – citrus, saline. Aged sur lie (on its yeast sediment), giving extra texture while staying fresh.',
    food_pairings: ['Oysters', 'shellfish', 'seafood'],
    upsell_tip: 'If they like this, the Sancerre (£78) is the next step up – same crisp acidity but more complexity and a prestigious name.',
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Vouvray Sec 'Chaflorie'",
    producer: "Clos de l'Épinay",
    vintage: 2024,
    region: 'Loire Valley',
    country: 'France',
    grape: 'Chenin Blanc',
    type: 'white',
    body: 'medium',
    bottle_price: 67,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium-bodied, fresh but textured – apple, honey, citrus. Chenin Blanc is one of the most versatile grapes – it can make dry, sweet, or sparkling wines.',
    food_pairings: ['Roast chicken', 'creamy dishes', 'poultry'],
    upsell_tip: "If they want more richness, the Sancerre 'Chavignol' (£90) or the Burgundy whites from Meursault or Puligny are natural steps up.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Sancerre 'Le Pierrier'",
    producer: 'Domaine Thomas',
    vintage: 2024,
    region: 'Loire Valley',
    country: 'France',
    grape: 'Sauvignon Blanc',
    type: 'white',
    body: 'medium',
    bottle_price: 78,
    glass_price: 21,
    carafe_price: 40,
    by_the_glass: true,
    coravin: false,
    tasting_notes: 'Crisp Sauvignon Blanc – citrus, green apple, flinty mineral. Sancerre is one of the benchmark regions for Sauvignon Blanc, known for its mineral-driven style. The flint character comes partly from the limestone soils.',
    food_pairings: ['Goat cheese', 'oysters', 'fresh salads', 'seafood', 'cheese'],
    upsell_tip: "For guests who love this, point them to the Sancerre 'Chavignol' by Gérard Boulay (£90). Boulay's is a step up in quality – old vines, more prestigious terroir (Kimmeridgian limestone), and considered by many to be 1er Cru quality.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Sancerre 'Chavignol'",
    producer: 'Gérard Boulay',
    vintage: 2024,
    region: 'Loire Valley',
    country: 'France',
    grape: 'Sauvignon Blanc',
    type: 'white',
    body: 'medium',
    bottle_price: 90,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Crisp Sauvignon Blanc – citrus, gooseberry, white flowers, flinty mineral. Grown on Kimmeridgian limestone soils. Gérard Boulay is one of the most respected names in Sancerre. Chavignol is a hamlet within Sancerre famed for Crottin de Chavignol goat cheese – the classic pairing.',
    food_pairings: ['Goat cheese', 'oysters', 'fresh seafood', 'cheese', 'seafood'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: 'Saumur-Champigny',
    producer: 'Domaine Côte des Roches Neuves',
    vintage: 2024,
    region: 'Loire Valley',
    country: 'France',
    grape: 'Cabernet Franc',
    type: 'red',
    body: 'medium',
    bottle_price: 56,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium-bodied Cabernet Franc – red cherry, raspberry, herbs, graphite, fresh. Thierry Germain at Roches Neuves is a biodynamic producer and one of the Loire\'s most acclaimed winemakers.',
    food_pairings: ['Roast pork', 'charcuterie', 'grilled vegetables', 'poultry', 'veg'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },

  // ===== BURGUNDY =====
  {
    name: 'Bourgogne Aligoté',
    producer: 'Fanny Sabre',
    vintage: 2022,
    region: 'Burgundy',
    country: 'France',
    grape: 'Aligoté',
    type: 'white',
    body: 'light',
    bottle_price: 66,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Light, zesty – lemon, green apple. Traditionally used in a Kir cocktail with blackcurrant liqueur. Aligoté is Burgundy\'s second white grape after Chardonnay – sharper and more citrus-driven. Fanny Sabre works with minimal intervention.',
    food_pairings: ['Oysters', 'seafood'],
    upsell_tip: 'A perfect gateway wine. If they enjoy the freshness, suggest stepping up to the Chablis (£75) for more complexity and prestige.',
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: 'Chablis',
    producer: 'Ventoura',
    vintage: 2023,
    region: 'Burgundy',
    country: 'France',
    grape: 'Chardonnay',
    type: 'white',
    body: 'light',
    bottle_price: 75,
    glass_price: 19.75,
    carafe_price: 38.50,
    by_the_glass: true,
    coravin: false,
    tasting_notes: 'Light, crisp Chardonnay – citrus, oyster shell. Chablis vineyards grow on ancient seabed limestone rich in fossils – this is why the wines taste saline. Chablis is unoaked, making it leaner and more mineral than most Burgundy Chardonnay.',
    food_pairings: ['Oysters', 'seafood'],
    upsell_tip: "Step up to the Chablis 1er Cru 'Les Serres' by Domaine Oudin (£95) – same style but more concentration and prestige from a classified vineyard.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Chablis 1er Cru 'Les Serres'",
    producer: 'Domaine Oudin',
    vintage: 2022,
    region: 'Burgundy',
    country: 'France',
    grape: 'Chardonnay',
    type: 'white',
    body: 'medium',
    bottle_price: 95,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium, mineral Chardonnay – lemon, stone fruit. Premier Cru (1er Cru) means a classified, higher-quality vineyard site within Chablis. There are 40 Premier Cru vineyards in Chablis but only 7 Grand Crus.',
    food_pairings: ['Scallops', 'grilled fish', 'seafood'],
    upsell_tip: "For guests wanting to go further, the Saint-Aubin 1er Cru (£115) offers similar quality with the richness of the Côte d'Or.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Pouilly-Fuissé 'Alliance' Vieilles Vignes",
    producer: 'Domaine Barraud',
    vintage: 2023,
    region: 'Burgundy',
    country: 'France',
    grape: 'Chardonnay',
    type: 'white',
    body: 'medium',
    bottle_price: 79,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium-full Chardonnay – ripe peach, pear, citrus, creamy texture, subtle oak. Made from vines 50–70 years old, which produce fewer grapes but with more concentration and depth.',
    food_pairings: ['Lobster', 'roast chicken', 'creamy sauces', 'seafood', 'poultry'],
    upsell_tip: 'If they like the richness here, Meursault (£185) is the ultimate expression of this style – nutty, buttery, world-class.',
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Saint-Aubin 1er Cru 'La Chateniêre'",
    producer: 'Henri Prudhon et Fils',
    vintage: 2023,
    region: 'Burgundy',
    country: 'France',
    grape: 'Chardonnay',
    type: 'white',
    body: 'medium',
    bottle_price: 115,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium-bodied Chardonnay – citrus, pear, butter, subtle oak, mineral edge. Saint-Aubin 1er Cru often delivers the richness of its famous neighbour Meursault at better value.',
    food_pairings: ['Roast chicken', 'creamy fish', 'lobster', 'seafood', 'poultry'],
    upsell_tip: "For guests who want the 'real' Meursault or Puligny experience, point them to Meursault (£185) or Puligny-Montrachet (£160) – same style, more prestige and depth.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Puligny-Montrachet 'Noyer Bret'",
    producer: 'François Legros',
    vintage: 2022,
    region: 'Burgundy',
    country: 'France',
    grape: 'Chardonnay',
    type: 'white',
    body: 'medium',
    bottle_price: 160,
    glass_price: 28.50,
    carafe_price: 81,
    by_the_glass: true,
    coravin: true,
    tasting_notes: 'Medium-full, refined Chardonnay – citrus, almond, mineral. Puligny-Montrachet is home to several Grand Cru vineyards including Le Montrachet, considered the greatest white wine vineyard on earth.',
    food_pairings: ['Premium seafood', 'scallops', 'creamy dishes', 'seafood'],
    upsell_tip: 'The next step up is the Corton-Charlemagne Grand Cru (£270) – one of Burgundy\'s most prestigious whites, full and powerful.',
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: 'Meursault',
    producer: 'Domaine Antoine Jobard',
    vintage: 2023,
    region: 'Burgundy',
    country: 'France',
    grape: 'Chardonnay',
    type: 'white',
    body: 'medium',
    bottle_price: 185,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium-full Chardonnay – lemon, hazelnut, butter, oak, saline finish. Meursault is famous for rich, textured Chardonnay with a signature nutty, buttery character. Antoine Jobard is one of Meursault\'s most respected producers.',
    food_pairings: ['Lobster', 'turbot', 'creamy sauces', 'seafood', 'poultry'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: 'Corton-Charlemagne Grand Cru',
    producer: 'Domaine Rollin',
    vintage: 2022,
    region: 'Burgundy',
    country: 'France',
    grape: 'Chardonnay',
    type: 'white',
    body: 'full',
    bottle_price: 270,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Full, powerful Chardonnay – citrus, toasted nuts, mineral. Grand Cru is the highest level in Burgundy – only 33 exist for reds, and only 8 for whites. Corton-Charlemagne spans the villages of Aloxe-Corton and Pernand-Vergelesses.',
    food_pairings: ['Premium seafood', 'truffle dishes', 'seafood'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: 'Bourgogne Rouge',
    producer: 'Fanny Sabre',
    vintage: 2022,
    region: 'Burgundy',
    country: 'France',
    grape: 'Pinot Noir',
    type: 'red',
    body: 'light',
    bottle_price: 75,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Light-medium Pinot Noir – red cherry, fresh. Bourgogne Rouge is the entry-level Burgundy appellation – a good honest introduction to how Burgundy Pinot Noir should taste before spending more.',
    food_pairings: ['Duck', 'roast chicken', 'poultry'],
    upsell_tip: 'A great gateway. Step up to the Santenay (£115) for a proper village Burgundy, or Auxey-Duresses (£130) for excellent value.',
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: 'Santenay',
    producer: 'Camille Giroud',
    vintage: 2022,
    region: 'Burgundy',
    country: 'France',
    grape: 'Pinot Noir',
    type: 'red',
    body: 'medium',
    bottle_price: 115,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium Pinot Noir – cherry, spice. Santenay is at the southern end of the Côte de Beaune and often offers great Burgundy value. Camille Giroud is a highly regarded Beaune négociant.',
    food_pairings: ['Duck', 'lamb'],
    upsell_tip: 'For a step up to more serious Burgundy, Gevrey-Chambertin (£160) or Nuits-Saint-Georges 1er Cru (£270) are the destinations.',
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: 'Auxey-Duresses',
    producer: 'Domaine Comte Armand',
    vintage: 2022,
    region: 'Burgundy',
    country: 'France',
    grape: 'Pinot Noir',
    type: 'red',
    body: 'medium',
    bottle_price: 130,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium Pinot Noir – red fruit, earthy. Auxey-Duresses sits next to Meursault, but is much less well-known – meaning much better value. Comte Armand is a top domaine based in Pommard.',
    food_pairings: ['Roast chicken', 'mushrooms', 'poultry', 'veg'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: 'Gevrey-Chambertin',
    producer: 'Domaine René Bouvier',
    vintage: 2021,
    region: 'Burgundy',
    country: 'France',
    grape: 'Pinot Noir',
    type: 'red',
    body: 'medium',
    bottle_price: 160,
    glass_price: 27.50,
    carafe_price: 78.50,
    by_the_glass: true,
    coravin: true,
    tasting_notes: 'Medium-full Pinot Noir – dark cherry, spice. Gevrey is the largest and most famous village in the Côte de Nuits. 2021 was a challenging vintage with low yields but produced elegant, concentrated wines.',
    food_pairings: ['Duck', 'venison', 'game', 'poultry'],
    upsell_tip: 'The ultimate step up is the Nuits-Saint-Georges 1er Cru (£270) – a prestigious village with a classified vineyard and a decade of age already on it.',
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Nuits-Saint-Georges 1er Cru",
    producer: "Domaine de l'Arlot",
    vintage: 2016,
    region: 'Burgundy',
    country: 'France',
    grape: 'Pinot Noir',
    type: 'red',
    body: 'full',
    bottle_price: 270,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Full, structured Pinot Noir – dark fruit, spice. 2016 is an excellent vintage in Burgundy – the wine has nearly 10 years of age and is drinking beautifully now. Domaine de l\'Arlot is a biodynamic estate. Worth mentioning the vintage maturity as a selling point.',
    food_pairings: ['Game', 'duck', 'poultry'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },

  // ===== BORDEAUX =====
  {
    name: 'Blaye Côtes de Bordeaux',
    producer: 'Domaine Cosse Maisonneuve',
    vintage: 2023,
    region: 'Bordeaux',
    country: 'France',
    grape: 'Sauvignon Blanc / Muscadelle',
    type: 'white',
    body: 'medium',
    bottle_price: 56,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium-bodied white – citrus, peach, light butter, subtle oak, floral notes. Muscadelle adds floral, honeyed notes. Cosse Maisonneuve is better known for its Cahors Malbec.',
    food_pairings: ['Roast chicken', 'creamy fish', 'soft cheeses', 'poultry', 'cheese'],
    upsell_tip: 'Guests who like this creamy white style should try the Pouilly-Fuissé (£79) or the Meursault (£185) for a purer, more serious version.',
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: 'Lalande de Pomerol',
    producer: 'Château Moncets',
    vintage: 2020,
    region: 'Bordeaux',
    country: 'France',
    grape: 'Merlot / Cabernet Franc',
    type: 'red',
    body: 'medium',
    bottle_price: 65,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium-full Merlot-led Bordeaux – plum, blackberry, soft spice, smooth tannins. Lalande-de-Pomerol offers a similar plush, Merlot-driven style to its famous neighbour Pomerol at a much friendlier price.',
    food_pairings: ['Roast lamb', 'duck', 'mushroom dishes', 'lamb', 'poultry'],
    upsell_tip: 'This is the perfect stepping stone to Pomerol (£160) – same Merlot character, but more depth, complexity and a famous appellation name.',
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: 'Saint-Émilion Grand Cru',
    producer: 'Château La Grave Figeac',
    vintage: 2019,
    region: 'Bordeaux',
    country: 'France',
    grape: 'Merlot / Cabernet Franc',
    type: 'red',
    body: 'medium',
    bottle_price: 98,
    glass_price: 18,
    carafe_price: 50,
    by_the_glass: true,
    coravin: true,
    tasting_notes: 'Medium-full Merlot-led Bordeaux – black cherry, plum, cedar, elegant structure. 2019 is an excellent vintage in Bordeaux – ripe, generous, with good structure. Note: Grand Cru in Saint-Émilion is not the same as Burgundy Grand Cru – it is a quality floor, not a rare distinction.',
    food_pairings: ['Beef fillet', 'lamb', 'aged cheeses', 'beef', 'cheese'],
    upsell_tip: 'Step up to the Pomerol (£160) for a more plush, velvety style, or the Saint-Julien Grand Cru Classé (£190) for more structure and prestige.',
    fix_tip: "Note: 'Grand Cru' in Saint-Émilion just means the wine was submitted for tasting approval – it's a quality floor, not a rare distinction like in Burgundy.",
    active: true,
    featured: false,
  },
  {
    name: 'Pomerol',
    producer: 'Château Gombaude-Guillot',
    vintage: 2017,
    region: 'Bordeaux',
    country: 'France',
    grape: 'Merlot / Cabernet Franc',
    type: 'red',
    body: 'medium',
    bottle_price: 160,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium-full Merlot-led Bordeaux – plum, blackberry, earth, velvety texture. Pomerol is dominated by Merlot, producing plush, rounded wines. It has no official classification – Pétrus is the most famous wine here. Gombaude-Guillot is a biodynamic estate.',
    food_pairings: ['Duck', 'roast beef', 'truffle dishes', 'beef', 'poultry'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: 'Saint-Estèphe',
    producer: 'Château Graves de Pez',
    vintage: 2020,
    region: 'Bordeaux',
    country: 'France',
    grape: 'Cabernet Sauvignon / Merlot / Petit Verdot',
    type: 'red',
    body: 'full',
    bottle_price: 78,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Full-bodied Cabernet Sauvignon-led Bordeaux – blackcurrant, cassis, graphite, firm tannins. Saint-Estèphe wines are typically more structured and powerful because of their clay-rich soils. Graves de Pez is a Cru Bourgeois.',
    food_pairings: ['Steak', 'braised beef', 'hearty stews', 'beef'],
    upsell_tip: "For guests who want the Grand Cru Classé experience, suggest the Margaux (£135) for elegance or the Saint-Julien (£190) for power and age.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Margaux 'Nout'",
    producer: 'Clos du Jaugueyron',
    vintage: 2018,
    region: 'Bordeaux',
    country: 'France',
    grape: 'Cabernet Sauvignon blend',
    type: 'red',
    body: 'medium',
    bottle_price: 135,
    glass_price: 24,
    carafe_price: 68.50,
    by_the_glass: true,
    coravin: true,
    tasting_notes: 'Medium-full Cabernet Sauvignon-led Bordeaux – red and black fruit, floral notes, silky tannins. 2018 is one of the best Bordeaux vintages of the decade – warm, ripe, generous. Clos du Jaugueyron is a small artisan estate in Margaux.',
    food_pairings: ['Lamb', 'duck', 'refined meat dishes', 'lamb', 'poultry'],
    upsell_tip: 'Point guests to the Saint-Julien Grand Cru Classé (£190) for an even more prestigious Left Bank experience.',
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: 'Saint-Julien Grand Cru Classé',
    producer: 'Château Branaire Ducru',
    vintage: 2009,
    region: 'Bordeaux',
    country: 'France',
    grape: 'Cabernet Sauvignon blend',
    type: 'red',
    body: 'full',
    bottle_price: 190,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Full-bodied Cabernet Sauvignon-led Bordeaux – cassis, cedar, tobacco, layered complexity. 2009 is a legendary Bordeaux vintage. Branaire Ducru is a 4th Growth Grand Cru Classé. This wine has 15+ years of age – it is drinking at peak right now.',
    food_pairings: ['Ribeye steak', 'venison', 'aged cheeses', 'beef', 'game', 'cheese'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },

  // ===== SOUTHERN FRANCE =====
  {
    name: "Corbières 'Lo Petit Fantet d'Hippolyte'",
    producer: 'Domaine Pierre Bories',
    vintage: 2024,
    region: 'Southern France',
    country: 'France',
    grape: 'Roussanne / Marsanne / Grenache Blanc / Grenache Gris',
    type: 'white',
    body: 'medium',
    bottle_price: 42,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium-bodied white blend – stone fruit, herbal notes, floral, textured palate. Corbières is traditionally a red wine region but is increasingly producing interesting white blends from Rhône grape varieties.',
    food_pairings: ['Grilled fish', 'Mediterranean vegetables', 'soft cheeses', 'seafood', 'veg', 'cheese'],
    upsell_tip: 'For guests who like texture, the Vouvray (£67) or Pouilly-Fuissé (£79) offer more complexity at a modest step up.',
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: 'Viognier',
    producer: 'Maison Bruyère & David',
    vintage: 2023,
    region: 'Southern France',
    country: 'France',
    grape: 'Viognier',
    type: 'white',
    body: 'medium',
    bottle_price: 62,
    glass_price: 17,
    carafe_price: 32,
    by_the_glass: true,
    coravin: false,
    tasting_notes: 'Medium-full, aromatic – apricot, peach, floral. Viognier nearly disappeared in the 1960s when only a handful of hectares remained in the Northern Rhône. It has low acidity – does NOT work well with high-acid dishes like tomatoes or vinaigrette.',
    food_pairings: ['Spiced dishes', 'roast chicken', 'poultry', 'spicy'],
    upsell_tip: null,
    fix_tip: 'Viognier has low acidity – avoid pairing with high-acid dishes (tomatoes, vinaigrette). Best with spice, cream, and rich poultry.',
    active: true,
    featured: false,
  },
  {
    name: 'Corbières Cuvée Classique',
    producer: 'Château Ollieux Romanis',
    vintage: 2022,
    region: 'Southern France',
    country: 'France',
    grape: 'Grenache / Mourvèdre / Syrah',
    type: 'red',
    body: 'medium',
    bottle_price: 43,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: "Medium-full Mediterranean blend – dark fruit, herbs (garrigue). 'Garrigue' is the local scrubland – thyme, rosemary, lavender – whose aromas come through in the wine. Ollieux Romanis is one of the top estates in Corbières, certified organic.",
    food_pairings: ['Lamb', 'grilled meats', 'lamb', 'beef'],
    upsell_tip: "Step up to the Côtes du Rhône (£55) or Châteauneuf-du-Pape (£115) for more complexity and prestige.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Malbec 'Le Combal'",
    producer: 'Domaine Cosse Maisonneuve',
    vintage: 2019,
    region: 'Southern France',
    country: 'France',
    grape: 'Malbec',
    type: 'red',
    body: 'full',
    bottle_price: 62,
    glass_price: 17,
    carafe_price: 32,
    by_the_glass: true,
    coravin: false,
    tasting_notes: 'Full, rich Malbec – blackberry, spice. Cahors is actually the original home of Malbec – it was taken to Argentina in the 19th century. French Malbec tends to be earthier and less fruity than Argentinian versions.',
    food_pairings: ['Steak', 'beef stew', 'beef'],
    upsell_tip: 'Guests who like bold reds should also consider the Châteauneuf-du-Pape (£115) for even more complexity.',
    fix_tip: null,
    active: true,
    featured: false,
  },

  // ===== REST OF FRANCE (Alsace, Jura, Beaujolais) =====
  {
    name: "Riesling 'Luss'",
    producer: 'Léon Boesch',
    vintage: 2022,
    region: 'Rest of France',
    country: 'France',
    grape: 'Riesling',
    type: 'white',
    body: 'medium',
    bottle_price: 70,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium, dry, aromatic – lime, mineral. Alsace Riesling is almost always completely dry, unlike many German Rieslings. Léon Boesch is a biodynamic estate.',
    food_pairings: ['Seafood', 'spicy food', 'seafood', 'spicy'],
    upsell_tip: "Step up to the Grand Cru Schoenenbourg (£115) for guests who want more intensity and age-worthiness.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Riesling Grand Cru 'Schoenenbourg'",
    producer: 'Domaine Marc Tempé',
    vintage: 2020,
    region: 'Rest of France',
    country: 'France',
    grape: 'Riesling',
    type: 'white',
    body: 'medium',
    bottle_price: 115,
    glass_price: 20,
    carafe_price: 58,
    by_the_glass: true,
    coravin: true,
    tasting_notes: 'Dry Riesling – lime, stone fruit, intense mineral. Schoenenbourg Grand Cru is historically the first Alsatian vineyard to be mentioned in writing (1348). Grand Cru Rieslings can age 20+ years. Marc Tempé is one of Alsace\'s most respected biodynamic producers.',
    food_pairings: ['Spicy Asian food', 'pork', 'shellfish', 'spicy', 'seafood'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: 'Beaujolais Rouge',
    producer: 'Château Cambon',
    vintage: 2024,
    region: 'Rest of France',
    country: 'France',
    grape: 'Gamay',
    type: 'red',
    body: 'light',
    bottle_price: 62,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Light-bodied Gamay – red cherry, raspberry, floral, fresh and juicy. Beaujolais Gamay is naturally low in tannins and can be served slightly chilled – a useful tip for warm weather service.',
    food_pairings: ['Charcuterie', 'roast chicken', 'light salads', 'poultry', 'veg'],
    upsell_tip: "For Beaujolais lovers, the Fleurie 'La Madone' (£80) is a step up to a named Cru – more complexity and elegance.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Fleurie 'La Madone'",
    producer: 'Domaine Chamonard',
    vintage: 2020,
    region: 'Rest of France',
    country: 'France',
    grape: 'Gamay',
    type: 'red',
    body: 'medium',
    bottle_price: 80,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Light-medium Gamay – red berries, violet, spice, silky texture. Can serve slightly chilled. Fleurie is often considered the most elegant and floral of the 10 Beaujolais Crus. Chamonard is a top natural wine estate.',
    food_pairings: ['Duck', 'pork', 'mushroom dishes', 'poultry', 'game'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Arbois 'Tradition'",
    producer: 'Domaine Villet',
    vintage: 2021,
    region: 'Rest of France',
    country: 'France',
    grape: 'Trousseau / Poulsard / Pinot Noir',
    type: 'red',
    body: 'light',
    bottle_price: 75,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Light Jura blend – wild strawberry, herbs. Jura wines are some of the rarest and most unusual in France – production is tiny and the grape varieties (Trousseau, Poulsard) are found almost nowhere else.',
    food_pairings: ['Charcuterie', 'chicken', 'poultry'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },

  // ===== RHÔNE VALLEY =====
  {
    name: 'Cuvée des Galets',
    producer: "Les Vignerons d'Estézargues",
    vintage: 2022,
    region: 'Rhône Valley',
    country: 'France',
    grape: 'Grenache / Syrah / Carignan',
    type: 'red',
    body: 'medium',
    bottle_price: 38,
    glass_price: 11,
    carafe_price: 20,
    by_the_glass: true,
    coravin: false,
    tasting_notes: 'Medium-bodied red blend – red berries, spice, garrigue, smooth tannins. The galets (large rounded pebbles) in Rhône vineyards absorb heat during the day and release it at night, helping grapes ripen fully.',
    food_pairings: ['Grilled meats', 'sausages', 'ratatouille', 'beef', 'veg'],
    upsell_tip: "Step up to the Côtes du Rhône 'Mistral' (£55) for a more complex, classic Rhône blend.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Côtes du Rhône 'Mistral'",
    producer: 'Domaine de Ferrand',
    vintage: 2024,
    region: 'Rhône Valley',
    country: 'France',
    grape: 'Grenache / Syrah / Carignan / Vaccarèse',
    type: 'red',
    body: 'medium',
    bottle_price: 55,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium-bodied classic Rhône blend – red fruit, spice, herbs, smooth tannins. Côtes du Rhône blends typically lead with Grenache (for fruit and alcohol) with Syrah adding structure and black pepper spice.',
    food_pairings: ['Grilled lamb', 'ratatouille', 'sausages', 'lamb', 'beef', 'veg'],
    upsell_tip: "Step up to the Crozes-Hermitage (£69) for 100% Syrah structure, or the Châteauneuf-du-Pape (£115) for the ultimate Southern Rhône expression.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Crozes-Hermitage 'Beaumont'",
    producer: 'Domaine Les Bruyères',
    vintage: 2024,
    region: 'Rhône Valley',
    country: 'France',
    grape: 'Syrah',
    type: 'red',
    body: 'medium',
    bottle_price: 69,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium-full Syrah – blackberry, black pepper. Northern Rhône Syrah is famous for its black pepper spice – this comes from a compound called rotundone, also found in black peppercorns. Crozes-Hermitage surrounds the famous Hermitage hill but the wines are more approachable and better value.',
    food_pairings: ['Duck', 'steak', 'poultry', 'beef'],
    upsell_tip: "Point Syrah lovers to the Châteauneuf-du-Pape (£115) for the Southern Rhône blend experience, or the premium Vieux Télégraphe (£170) for an aged, full-bodied masterpiece.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Châteauneuf-du-Pape 'Habemus Papem'",
    producer: 'Domaine Santa Duc',
    vintage: 2021,
    region: 'Rhône Valley',
    country: 'France',
    grape: 'Grenache / Syrah',
    type: 'red',
    body: 'full',
    bottle_price: 115,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: "Full-bodied Southern Rhône blend – ripe red and black fruit, garrigue, pepper, powerful. 2021 was a cooler year so this is slightly lighter-bodied than typical. Châteauneuf-du-Pape can use up to 13 different grape varieties. Santa Duc is a biodynamic estate run by Yves Gras.",
    food_pairings: ['Game meats', 'stews', 'slow-roasted dishes', 'game', 'beef'],
    upsell_tip: "Step up to the Vieux Télégraphe (£170) for the most prestigious and complex expression of Châteauneuf on our list.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Châteauneuf-du-Pape 'Vieux Télégraphe'",
    producer: 'Famille Brunier',
    vintage: 2016,
    region: 'Rhône Valley',
    country: 'France',
    grape: 'Grenache / Mourvèdre / Syrah / Cinsault / Clairette',
    type: 'red',
    body: 'full',
    bottle_price: 170,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Full-bodied, structured blend – dark fruit, leather, herbs, long ageing potential. Our most full-bodied Rhône wine. Vieux Télégraphe is one of Châteauneuf\'s most prestigious estates, with vines on the famous La Crau plateau. 2016 is an excellent Rhône vintage.',
    food_pairings: ['Venison', 'braised beef', 'rich casseroles', 'game', 'beef'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },

  // ===== GERMANY & AUSTRIA =====
  {
    name: 'Riesling',
    producer: 'Weingut Knauss',
    vintage: 2023,
    region: 'Germany',
    country: 'Germany',
    grape: 'Riesling',
    type: 'white',
    body: 'light',
    bottle_price: 50,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Light-medium, aromatic – lime, apple. Knauss is in Württemberg, a lesser-known region making excellent dry Riesling. German dry Rieslings are labelled "trocken". If guests worry about sweetness, reassure them this is fully dry.',
    food_pairings: ['Spicy dishes', 'seafood', 'spicy', 'seafood'],
    upsell_tip: "Step up to the Alsace Grand Cru Riesling (£115) for guests who want more intensity and complexity.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Grüner Veltliner 'Potato Land'",
    producer: 'Matthias Warnung',
    vintage: 2023,
    region: 'Austria',
    country: 'Austria',
    grape: 'Grüner Veltliner',
    type: 'white',
    body: 'medium',
    bottle_price: 53,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium, fresh – citrus, white pepper. Grüner Veltliner is Austria\'s most famous grape – and one of the best food wines in the world due to its high acidity and white pepper character. Works brilliantly with vegetables, bitter greens and asparagus.',
    food_pairings: ['Schnitzel', 'seafood', 'poultry', 'veg'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },

  // ===== RIOJA =====
  {
    name: 'Rioja Blanco',
    producer: 'Remelluri',
    vintage: 2022,
    region: 'Rioja',
    country: 'Spain',
    grape: 'Complex white blend',
    type: 'white',
    body: 'medium',
    bottle_price: 138,
    glass_price: 23,
    carafe_price: 69,
    by_the_glass: true,
    coravin: true,
    tasting_notes: 'Complex white blend – citrus, stone fruit, herbal, subtle oak. Remelluri is one of Rioja\'s most prestigious estates, based in Rioja Alavesa (the coolest, most elegant sub-zone). Their white is made from a complex blend of old-vine white grapes.',
    food_pairings: ['Grilled fish', 'roasted poultry', 'tapas', 'seafood', 'poultry'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Rioja Reserva 'Solar de Randez'",
    producer: 'Bodegas Las Orcas',
    vintage: 2017,
    region: 'Rioja',
    country: 'Spain',
    grape: 'Tempranillo',
    type: 'red',
    body: 'medium',
    bottle_price: 62,
    glass_price: 16.75,
    carafe_price: 32,
    by_the_glass: true,
    coravin: false,
    tasting_notes: 'Medium-full, smooth Rioja – vanilla, red fruit. Rioja Reserva must be aged for at least 3 years before release, with at least 1 year in oak barrels. Bodegas Las Orcas is in Rioja Alavesa, the smallest and coolest sub-zone.',
    food_pairings: ['Lamb', 'pork', 'lamb'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },

  // ===== SPAIN & PORTUGAL =====
  {
    name: "Verdejo 'Cucú'",
    producer: 'Barco del Corneta',
    vintage: 2024,
    region: 'Spain & Portugal',
    country: 'Spain',
    grape: 'Verdejo',
    type: 'white',
    body: 'light',
    bottle_price: 49,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Light-medium white – citrus, green apple, fennel, herbal notes, fresh and crisp. Barco del Corneta is one of Spain\'s most celebrated natural wine producers. Often suggested as an alternative for Sauvignon Blanc drinkers. The slight bitterness on the finish is a quality marker, not a fault.',
    food_pairings: ['Seafood', 'salads', 'grilled vegetables', 'seafood', 'veg'],
    upsell_tip: "Step up to the Albariño (£66) for guests who want more stone fruit and salinity.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Albariño 'O Casal'",
    producer: 'Bodegas Boado Chaves',
    vintage: 2023,
    region: 'Spain & Portugal',
    country: 'Spain',
    grape: 'Albariño',
    type: 'white',
    body: 'light',
    bottle_price: 66,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Light-medium, fresh – citrus, peach, saline. Albariño is grown close to the Atlantic Ocean in Rías Baixas, giving it a distinct salty, coastal character. Very popular with guests who like Pinot Grigio but want more flavour.',
    food_pairings: ['Seafood', 'oysters', 'seafood'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Douro Branco 'Sondha'",
    producer: 'Triangle Wines',
    vintage: 2022,
    region: 'Spain & Portugal',
    country: 'Portugal',
    grape: 'Rabigato / Viosinho / Codega do Larinho',
    type: 'white',
    body: 'medium',
    bottle_price: 55,
    glass_price: 15.25,
    carafe_price: 28.50,
    by_the_glass: true,
    coravin: false,
    tasting_notes: 'Aromatic white blend – citrus, mineral, lightly oaked, creamy. All three grapes are indigenous to the Douro and rarely found outside Portugal. The Douro Valley is world-famous for Port, but dry white wines from indigenous Portuguese grapes are becoming increasingly celebrated.',
    food_pairings: ['Seafood', 'grilled vegetables', 'light poultry', 'seafood', 'veg', 'poultry'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: 'Alvarinho',
    producer: 'Pequenos Rebentos',
    vintage: 2024,
    region: 'Spain & Portugal',
    country: 'Portugal',
    grape: 'Alvarinho',
    type: 'white',
    body: 'light',
    bottle_price: 52,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Light, crisp, aromatic – lime, peach. Alvarinho is the same grape as Albariño in Spain. Vinho Verde literally means "green wine" – referring to its fresh, youthful character, not the colour.',
    food_pairings: ['Seafood', 'shellfish', 'seafood'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: 'Mencía Joven',
    producer: 'Guímaro',
    vintage: 2024,
    region: 'Spain & Portugal',
    country: 'Spain',
    grape: 'Mencía',
    type: 'red',
    body: 'light',
    bottle_price: 49,
    glass_price: 13.75,
    carafe_price: 25.50,
    by_the_glass: true,
    coravin: false,
    tasting_notes: 'Light-bodied Mencía – red cherry, cranberry, floral, herbal notes, very fresh. Similar to a light Chianti. Ribeira Sacra vineyards are some of the steepest in the world – all harvesting must be done by hand. Can serve slightly chilled.',
    food_pairings: ['Charcuterie', 'grilled vegetables', 'light pork', 'veg', 'poultry'],
    upsell_tip: "Step up to the Dão Tinto (£48) for more structure, or the Garnacha (£45) for something fruitier.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: 'Garnacha',
    producer: 'Viña Zorzal',
    vintage: 2024,
    region: 'Spain & Portugal',
    country: 'Spain',
    grape: 'Garnacha',
    type: 'red',
    body: 'medium',
    bottle_price: 45,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium, juicy Garnacha – strawberry, spice. Viña Zorzal is in Navarra, north of Rioja. Spanish Garnacha tends to be riper and bolder than French Grenache. Good entry-level red for guests who want something approachable and fruity.',
    food_pairings: ['Tapas', 'grilled pork', 'beef', 'poultry'],
    upsell_tip: "Step up to the Rioja Reserva (£62) for a more structured, oak-aged Spanish red.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: 'Dão Tinto',
    producer: 'Alvaro Castro',
    vintage: 2022,
    region: 'Spain & Portugal',
    country: 'Portugal',
    grape: 'Portuguese blend',
    type: 'red',
    body: 'medium',
    bottle_price: 48,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium-bodied blend – red berries, herbal notes, balanced acidity, fine tannins. Dão is a cool, mountainous region in central Portugal – the wines have natural freshness and are built for ageing. Alvaro Castro is considered one of Portugal\'s greatest winemakers.',
    food_pairings: ['Roast pork', 'mushroom dishes', 'poultry', 'veg'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },

  // ===== NORTHERN ITALY =====
  {
    name: "Gavi 'Yellow Label'",
    producer: 'La Mesma',
    vintage: 2024,
    region: 'Northern Italy',
    country: 'Italy',
    grape: 'Cortese',
    type: 'white',
    body: 'light',
    bottle_price: 60,
    glass_price: 16.50,
    carafe_price: 31,
    by_the_glass: true,
    coravin: false,
    tasting_notes: 'Light, crisp Italian white – citrus, almond. This Gavi is made outside the village of Gavi itself, which is why it is labelled "Gavi" rather than "Gavi di Gavi" – the more prestigious sub-zone.',
    food_pairings: ['Seafood', 'salads', 'seafood', 'veg'],
    upsell_tip: "Step up to the Verdicchio (£46) or Chablis (£75) for more complexity at a similar or higher price.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Barbera 'Brich'",
    producer: 'Agricola Gaia',
    vintage: 2024,
    region: 'Northern Italy',
    country: 'Italy',
    grape: 'Barbera',
    type: 'red',
    body: 'medium',
    bottle_price: 47,
    glass_price: 13.25,
    carafe_price: 24.50,
    by_the_glass: true,
    coravin: false,
    tasting_notes: 'Medium, juicy Barbera – cherry, bright acidity. Barbera has very high natural acidity – this makes it extremely food-friendly, cutting through fat and richness. A great wine to suggest with rich food – the acidity acts like a squeeze of lemon.',
    food_pairings: ['Pasta', 'pizza', 'burgers', 'rich foods', 'pasta', 'beef'],
    upsell_tip: "Step up to the Langhe Nebbiolo (£60) for more structure and the beginning of the Barolo/Barbaresco experience.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Langhe Nebbiolo 'Baluma'",
    producer: 'Diego Conterno',
    vintage: 2020,
    region: 'Northern Italy',
    country: 'Italy',
    grape: 'Nebbiolo',
    type: 'red',
    body: 'medium',
    bottle_price: 60,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium-full Nebbiolo – rose petals, cherry, tannin. Often called "baby Barolo" – this is young, unoaked Nebbiolo from the Langhe hills. Diego Conterno is a highly regarded Barolo producer. A perfect introduction to Nebbiolo before committing to a full Barolo.',
    food_pairings: ['Lamb', 'beef', 'truffle', 'mushrooms', 'lamb', 'beef', 'veg'],
    upsell_tip: "This is the ideal stepping stone to the Barolo Undici Comuni (£105) – same grape, same producer style, much more complexity.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: 'Barolo Undici Comuni',
    producer: 'Arnaldo Rivera',
    vintage: 2020,
    region: 'Northern Italy',
    country: 'Italy',
    grape: 'Nebbiolo',
    type: 'red',
    body: 'full',
    bottle_price: 105,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Full-bodied Nebbiolo – rose petals, tar, cherry, firm tannins, high acidity. Barolo must be 100% Nebbiolo and aged for at least 38 months. "Undici Comuni" means 11 villages – the blend comes from across the entire Barolo DOCG. 2020 is an excellent, warm vintage for Barolo.',
    food_pairings: ['Truffle dishes', 'braised beef', 'aged cheeses', 'beef', 'cheese'],
    upsell_tip: "Step up to the single-vineyard Barolo 'Rocche dell'Annunziata' by Renato Molino (£150) for a more prestigious, terroir-specific expression.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Barolo 'Rocche dell'Annunziata'",
    producer: 'Renato Molino',
    vintage: 2017,
    region: 'Northern Italy',
    country: 'Italy',
    grape: 'Nebbiolo',
    type: 'red',
    body: 'full',
    bottle_price: 150,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: "Full Nebbiolo – rose petals, tar, cherry. Rocche dell'Annunziata is one of Barolo's most prestigious single vineyards, located in the commune of La Morra. 2017 was a warm vintage in Barolo – wines are more approachable young than usual.",
    food_pairings: ['Steak', 'truffle dishes', 'beef'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Valpolicella Classico 'Velluto'",
    producer: 'Meroni',
    vintage: 2024,
    region: 'Northern Italy',
    country: 'Italy',
    grape: 'Corvina / Corvinone / Molinara / Rondinella',
    type: 'red',
    body: 'medium',
    bottle_price: 54,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium Italian red – sour cherry, herbs. Valpolicella Classico comes from the original, hillside Classico zone. The same grapes used for this wine are also used for Amarone – but here they\'re fermented fresh, giving a light, easy-drinking style.',
    food_pairings: ['Pizza', 'pasta', 'pasta'],
    upsell_tip: "This is the natural stepping stone to the Amarone (£95) – same grapes but made from dried fruit, giving an extraordinary intensity and power.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: 'Amarone della Valpolicella',
    producer: 'Corte Lenguin',
    vintage: 2020,
    region: 'Northern Italy',
    country: 'Italy',
    grape: 'Corvina / Corvinone / Rondinella',
    type: 'red',
    body: 'full',
    bottle_price: 95,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Full-bodied red – dried cherry, plum, raisin, chocolate, spice, rich and powerful. Amarone is made using the appassimento method – grapes are partially dried for several months before pressing, concentrating the sugars and flavours dramatically.',
    food_pairings: ['Braised beef', 'game', 'aged cheeses', 'beef', 'game', 'cheese'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },

  // ===== CENTRAL ITALY =====
  {
    name: "Falerio 'Oris'",
    producer: 'Ciù Ciù',
    vintage: 2024,
    region: 'Central Italy',
    country: 'Italy',
    grape: 'Passerina / Trebbiano / Pecorino',
    type: 'white',
    body: 'light',
    bottle_price: 38,
    glass_price: 11.50,
    carafe_price: 21,
    by_the_glass: true,
    coravin: false,
    tasting_notes: 'Light-medium, fresh – citrus, floral, tropical fruits. Pecorino (the grape, not the cheese) is named after sheep – pecora in Italian – because sheep used to graze around the vineyards. Great talking point. Good value entry-level Italian white.',
    food_pairings: ['Fish', 'salads', 'seafood', 'veg'],
    upsell_tip: "Step up to the Verdicchio (£46) for more complexity from the same region.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Verdicchio 'Di Gino'",
    producer: 'Fattoria San Lorenzo',
    vintage: 2024,
    region: 'Central Italy',
    country: 'Italy',
    grape: 'Verdicchio',
    type: 'white',
    body: 'medium',
    bottle_price: 46,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium, fresh, mineral – lemon, almond. Verdicchio wines can age surprisingly well for an Italian white. Verdicchio has a distinctive slight bitterness on the finish – a quality marker. The name comes from "verde" (green) – the wine has a slight green tinge when young.',
    food_pairings: ['Seafood', 'pasta', 'seafood', 'pasta'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Toscana Rosso 'Fla Vino'",
    producer: 'La Palazzetta',
    vintage: 2024,
    region: 'Central Italy',
    country: 'Italy',
    grape: 'Sangiovese',
    type: 'red',
    body: 'medium',
    bottle_price: 57,
    glass_price: 15.75,
    carafe_price: 29.50,
    by_the_glass: true,
    coravin: false,
    tasting_notes: 'Medium-bodied Sangiovese – sour cherry, violet, earthy spice, bright acidity. La Palazzetta is a top Brunello producer based in Montalcino. This IGT is their everyday Sangiovese – great value from a prestige producer.',
    food_pairings: ['Pasta with tomato sauce', 'grilled meats', 'antipasti', 'pasta', 'beef', 'veg'],
    upsell_tip: "This is an ideal gateway to the Chianti Classico (£67) and then the Brunello di Montalcino (£130).",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: 'Chianti Classico',
    producer: 'Poggerino',
    vintage: 2023,
    region: 'Central Italy',
    country: 'Italy',
    grape: 'Sangiovese',
    type: 'red',
    body: 'medium',
    bottle_price: 67,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium-full Sangiovese – cherry, herbs. Chianti Classico wines carry the Black Rooster (Gallo Nero) symbol. Classico is the original, hillside sub-zone of Chianti. Poggerino is a top biodynamic estate in Radda in Chianti.',
    food_pairings: ['Pasta', 'steak', 'pasta', 'beef'],
    upsell_tip: "Step up to the Brunello di Montalcino by Padaletti (£130) for the full, aged expression of Tuscany's greatest red grape.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: 'Brunello di Montalcino',
    producer: 'Padaletti',
    vintage: 2017,
    region: 'Central Italy',
    country: 'Italy',
    grape: 'Sangiovese',
    type: 'red',
    body: 'full',
    bottle_price: 130,
    glass_price: 23.50,
    carafe_price: 66,
    by_the_glass: true,
    coravin: true,
    tasting_notes: 'Full-bodied Sangiovese – dark cherry, dried herbs, leather, structured tannins. Brunello di Montalcino must be 100% Sangiovese and aged for at least 5 years before release (6 for Riserva). Padaletti is one of the oldest Brunello producers.',
    food_pairings: ['Bistecca', 'game meats', 'aged cheeses', 'beef', 'game', 'cheese'],
    upsell_tip: "Step up to the Brunello 'Ugolaia' by Lisini (£250) for a prestigious single-vineyard version from one of Montalcino's most revered estates.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Brunello di Montalcino 'Ugolaia'",
    producer: 'Lisini',
    vintage: 2017,
    region: 'Central Italy',
    country: 'Italy',
    grape: 'Sangiovese',
    type: 'red',
    body: 'full',
    bottle_price: 250,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Full, powerful Sangiovese – dark cherry, spice. Lisini is one of Montalcino\'s oldest and most respected estates, certified organic. "Ugolaia" is their top single-vineyard wine. 2017 gives a rich, approachable style for Brunello. A genuine showpiece wine.',
    food_pairings: ['Steak', 'game', 'beef', 'game'],
    upsell_tip: "The next step is the Tignanello (£360) – one of the most famous Super Tuscans in the world.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: 'Bolgheri Rosso',
    producer: 'Le Macchiole',
    vintage: 2022,
    region: 'Central Italy',
    country: 'Italy',
    grape: 'Merlot / Syrah / Cabernet Franc / Cabernet Sauvignon',
    type: 'red',
    body: 'medium',
    bottle_price: 78,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium-full Bordeaux-style blend – blackcurrant, plum, spice, polished tannins. Bolgheri is known for "Super Tuscan" wines – Italian wines using international grape varieties like Cabernet and Merlot, which were revolutionary when introduced in the 1970s.',
    food_pairings: ['Grilled steak', 'lamb', 'rich pasta', 'beef', 'lamb', 'pasta'],
    upsell_tip: "Step up to the Tignanello (£360) for the ultimate Super Tuscan experience.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: 'Tignanello',
    producer: 'Antinori',
    vintage: 2018,
    region: 'Central Italy',
    country: 'Italy',
    grape: 'Sangiovese / Cabernet Sauvignon / Cabernet Franc',
    type: 'red',
    body: 'full',
    bottle_price: 360,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Full-bodied Super Tuscan – dark fruit, tobacco, cedar. Tignanello was one of the first "Super Tuscans" – it broke Italian wine law in the 1970s by blending Sangiovese with Cabernet Sauvignon and ageing in small French oak barriques. The Antinori family have been making wine in Florence since 1385.',
    food_pairings: ['Premium steak', 'beef'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },

  // ===== SOUTHERN ITALY =====
  {
    name: "Grillo 'Vigna Verde'",
    producer: 'Marco de Bartoli',
    vintage: 2023,
    region: 'Southern Italy',
    country: 'Italy',
    grape: 'Grillo',
    type: 'white',
    body: 'medium',
    bottle_price: 62,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium, Mediterranean – citrus, peach. Grillo was traditionally used for Marsala production but has been rediscovered as a serious dry white grape in Sicily. Marco de Bartoli is one of Sicily\'s most revered producers.',
    food_pairings: ['Seafood', 'grilled fish', 'seafood'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: 'Primitivo Gioia del Colle',
    producer: 'Fatalone',
    vintage: 2024,
    region: 'Southern Italy',
    country: 'Italy',
    grape: 'Primitivo',
    type: 'red',
    body: 'full',
    bottle_price: 64,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Full-bodied red – ripe blackberry, plum, spice, warm and plush. Primitivo is genetically identical to Zinfandel in California. Gioia del Colle is a cooler, higher-altitude zone – Fatalone intentionally harvests early to produce a lighter, fresher style than typical southern Primitivo.',
    food_pairings: ['BBQ meats', 'roasted lamb', 'hearty pasta', 'beef', 'lamb', 'pasta'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },

  // ===== GREECE =====
  {
    name: "Xinomavro 'Skyphos'",
    producer: 'Artisans Vigneros de Naoussa',
    vintage: 2022,
    region: 'Greece',
    country: 'Greece',
    grape: 'Xinomavro',
    type: 'red',
    body: 'medium',
    bottle_price: 52,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium-bodied, structured red – red cherry, tomato leaf, olive, high acidity, firm tannins. Xinomavro (ksee-NO-mah-vro) is often compared to Nebbiolo – both have very high acidity and tannins. Xinomavro literally means "acid black" in Greek.',
    food_pairings: ['Lamb', 'slow-cooked beef', 'tomato-based dishes', 'lamb', 'beef'],
    upsell_tip: "Nebbiolo fans who discover this should try the Barolo (£105+) to see the similarities.",
    fix_tip: null,
    active: true,
    featured: false,
  },

  // ===== NEW WORLD (Argentina, South Africa, New Zealand) =====
  {
    name: 'Sémillon-Torrontés',
    producer: 'Ballena del Sur',
    vintage: 2024,
    region: 'New World',
    country: 'Argentina',
    grape: 'Sémillon / Torrontés',
    type: 'white',
    body: 'medium',
    bottle_price: 37,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium, aromatic – citrus, floral. Torrontés is Argentina\'s signature aromatic white grape – possibly descended from Muscat brought by Spanish missionaries. Good value entry point.',
    food_pairings: ['Spicy dishes', 'seafood', 'spicy', 'seafood'],
    upsell_tip: "Step up to the South African Chenin Blanc (£46) for more depth and structure.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Chenin Blanc 'Die Kluise'",
    producer: 'Swartland & Paarl',
    vintage: 2023,
    region: 'New World',
    country: 'South Africa',
    grape: 'Chenin Blanc',
    type: 'white',
    body: 'medium',
    bottle_price: 46,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Structured Chenin Blanc – citrus, quince, subtle honey, mineral finish. South Africa has more old-vine Chenin Blanc than the Loire Valley. Old vines produce fewer grapes but more concentrated, complex wine. The Swartland has become a world-renowned region for natural wine.',
    food_pairings: ['Roast chicken', 'pork', 'creamy sauces', 'poultry'],
    upsell_tip: "Step up to the Rocking Horse Cape White Blend (£69) for more complexity from the same region.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "'Rocking Horse' Cape White Blend",
    producer: 'Thorne & Daughters',
    vintage: 2023,
    region: 'New World',
    country: 'South Africa',
    grape: 'Roussanne / Chenin Blanc / Chardonnay',
    type: 'white',
    body: 'medium',
    bottle_price: 69,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium-bodied white blend – stone fruit, floral notes, citrus, balanced oak. Thorne & Daughters is one of South Africa\'s most acclaimed natural wine producers, based in the Western Cape. This wine consistently receives outstanding reviews internationally.',
    food_pairings: ['Rich seafood', 'roast poultry', 'creamy dishes', 'seafood', 'poultry'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: 'Sauvignon Blanc',
    producer: 'Te Whare Ra',
    vintage: 2023,
    region: 'New World',
    country: 'New Zealand',
    grape: 'Sauvignon Blanc',
    type: 'white',
    body: 'light',
    bottle_price: 52,
    glass_price: 14.50,
    carafe_price: 27,
    by_the_glass: true,
    coravin: false,
    tasting_notes: 'Light, vibrant – passionfruit, lime. Marlborough Sauvignon Blanc is intensely aromatic – it has more tropical fruit and less of the grassy, flinty character of Sancerre. Te Whare Ra (TWR) is a biodynamic estate in Marlborough.',
    food_pairings: ['Goat cheese', 'seafood', 'seafood', 'cheese'],
    upsell_tip: "For guests who want more complexity from Sauvignon Blanc, the Sancerre (£78 or £90) is the classic step up.",
    fix_tip: null,
    active: true,
    featured: false,
  },

  // ===== AUSTRALIA =====
  {
    name: 'Chardonnay',
    producer: 'Commune of Buttons',
    vintage: 2021,
    region: 'Australia',
    country: 'Australia',
    grape: 'Chardonnay',
    type: 'white',
    body: 'medium',
    bottle_price: 75,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium, fresh – citrus, mineral. Adelaide Hills is one of Australia\'s coolest wine regions – sitting at high altitude, it produces Chardonnay with more European elegance. This is far removed from the big, buttery Australian Chardonnay stereotype.',
    food_pairings: ['Fish', 'chicken', 'seafood', 'poultry'],
    upsell_tip: "Step up to the Burgundy whites (from £75) for the European benchmarks.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Pinot Noir 'Lantern'",
    producer: 'La Maison de Ong',
    vintage: 2019,
    region: 'Australia',
    country: 'Australia',
    grape: 'Pinot Noir',
    type: 'red',
    body: 'light',
    bottle_price: 95,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Light-medium Pinot Noir – red cherry, cranberry, spice, silky texture. Yarra Valley is one of Australia\'s leading cool-climate regions for elegant Pinot Noir. 2019 was a warm, ripe vintage in Australia.',
    food_pairings: ['Duck', 'mushroom dishes', 'roast chicken', 'poultry', 'game'],
    upsell_tip: "For Pinot Noir fans, the Burgundy reds (from £75) or Oregon Pinot Noir (£68) offer the classic benchmark.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Cabernet Sauvignon 'Halcyon'",
    producer: 'Si Vintners',
    vintage: 2018,
    region: 'Australia',
    country: 'Australia',
    grape: 'Cabernet Sauvignon',
    type: 'red',
    body: 'full',
    bottle_price: 110,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Full-bodied Cabernet Sauvignon – blackcurrant, cassis, graphite, cedar, fine tannins. Margaret River is one of Australia\'s finest Cabernet Sauvignon regions, with a climate influenced by two oceans. 2018 was an excellent vintage.',
    food_pairings: ['Steak', 'lamb', 'hard cheeses', 'beef', 'lamb', 'cheese'],
    upsell_tip: "Compare with the Bordeaux Saint-Julien (£190) for a classic French version of the same grape.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Syrah 'Genesis'",
    producer: 'Castagna',
    vintage: 2018,
    region: 'Australia',
    country: 'Australia',
    grape: 'Syrah',
    type: 'red',
    body: 'medium',
    bottle_price: 140,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: "Medium-full Syrah – dark berries, pepper, olive, fine tannins. Beechworth's altitude and cooler climate produce more restrained, European-style Syrah – quite different from the big, jammy Barossa Shiraz most people associate with Australia. Castagna is a biodynamic estate.",
    food_pairings: ['Lamb', 'venison', 'slow-cooked stews', 'lamb', 'game'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },

  // ===== USA =====
  {
    name: "Chardonnay 'Seven Springs Vineyard'",
    producer: 'Evening Land',
    vintage: 2021,
    region: 'USA',
    country: 'USA',
    grape: 'Chardonnay',
    type: 'white',
    body: 'medium',
    bottle_price: 95,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium, elegant – citrus, hazelnut. Oregon Chardonnay is increasingly praised for its Burgundy-like elegance – cooler than California, with less oak and more minerality. Evening Land is partly backed by a Burgundian producer and makes wine in a deliberately French style.',
    food_pairings: ['Seafood', 'roast chicken', 'seafood', 'poultry'],
    upsell_tip: "Step up to the California Chardonnay (£140) for a richer, more classic California style.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Chardonnay 'Highland Divide'",
    producer: 'DuMOL',
    vintage: 2020,
    region: 'USA',
    country: 'USA',
    grape: 'Chardonnay',
    type: 'white',
    body: 'full',
    bottle_price: 140,
    glass_price: 25,
    carafe_price: 71,
    by_the_glass: true,
    coravin: true,
    tasting_notes: 'Full, rich – stone fruit, butter. DuMOL is one of California\'s most acclaimed Chardonnay and Pinot Noir producers. This is rich, buttery California Chardonnay at its best. The cool Russian River Valley, within Sonoma County, is one of California\'s best areas for Chardonnay.',
    food_pairings: ['Lobster', 'creamy dishes', 'seafood', 'poultry'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Pinot Noir 'Evolution'",
    producer: 'Dundee Hills',
    vintage: 2023,
    region: 'USA',
    country: 'USA',
    grape: 'Pinot Noir',
    type: 'red',
    body: 'medium',
    bottle_price: 68,
    glass_price: 18.50,
    carafe_price: 35,
    by_the_glass: true,
    coravin: false,
    tasting_notes: 'Medium, elegant Pinot – cherry, cranberry. Dundee Hills is considered the heart of the Willamette Valley and produces Oregon\'s most Burgundian Pinot Noirs. Oregon Pinot Noir is often compared to Burgundy – cooler climate, more earthy and restrained than California Pinot.',
    food_pairings: ['Duck', 'chicken', 'poultry'],
    upsell_tip: "Step up to the Ceritas single-vineyard Sonoma Coast Pinot Noir (£180) for the premium California expression.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Pinot Noir 'Vino De Los Ranchos'",
    producer: 'Scar of the Sea',
    vintage: 2023,
    region: 'USA',
    country: 'USA',
    grape: 'Pinot Noir',
    type: 'red',
    body: 'medium',
    bottle_price: 135,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium coastal Pinot – red fruit, mineral. Scar of the Sea is a celebrated natural wine producer. Santa Maria Valley is cooler than most of California due to its east-west orientation funnelling ocean air.',
    food_pairings: ['Duck', 'mushrooms', 'poultry', 'game'],
    upsell_tip: "Step up to the Ceritas Sonoma Coast (£180) for a more complex, premium expression.",
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Pinot Noir 'Elliott Vineyard'",
    producer: 'Ceritas',
    vintage: 2020,
    region: 'USA',
    country: 'USA',
    grape: 'Pinot Noir',
    type: 'red',
    body: 'medium',
    bottle_price: 180,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Medium-full premium Pinot – red fruit, spice. Ceritas produces tiny quantities of single-vineyard wines from the Sonoma Coast – one of California\'s most exciting Pinot regions. A showpiece wine.',
    food_pairings: ['Game', 'duck', 'game', 'poultry'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },
  {
    name: "Syrah 'Relentless'",
    producer: 'Shafer',
    vintage: 2016,
    region: 'USA',
    country: 'USA',
    grape: 'Syrah',
    type: 'red',
    body: 'full',
    bottle_price: 210,
    glass_price: null,
    carafe_price: null,
    by_the_glass: false,
    coravin: false,
    tasting_notes: 'Full-bodied Syrah – blackberry, smoked meat, pepper, rich and powerful. Shafer is a legendary Napa Valley producer, most famous for Hillside Select Cabernet. "Relentless" was created as a Syrah passion project. 2016 is an outstanding Napa vintage. This wine has 8+ years of age and is drinking beautifully.',
    food_pairings: ['BBQ ribs', 'lamb', 'game meats', 'beef', 'lamb', 'game'],
    upsell_tip: null,
    fix_tip: null,
    active: true,
    featured: false,
  },
]

// Seed function — call this from admin panel
export async function seedDatabase(supabase, propertyId) {
  const wines = seedWines.map(w => ({ ...w, property_id: propertyId }))
  const { data, error } = await supabase.from('wines').insert(wines).select()
  return { data, error }
}
