// Static wine region education data for the interactive world map
// ISO 3166-1 numeric codes used to match world-atlas topojson feature IDs

export const WINE_COUNTRIES = {
  '250': {
    name: 'France',
    flag: '🇫🇷',
    iso3: 'FRA',
    climate: 'Temperate maritime to continental; varies enormously from the cool Loire and Champagne in the north to Mediterranean Provence and Languedoc in the south.',
    keyGrapes: ['Chardonnay', 'Pinot Noir', 'Cabernet Sauvignon', 'Merlot', 'Sauvignon Blanc', 'Syrah', 'Grenache', 'Chenin Blanc', 'Riesling (Alsace)', 'Gamay'],
    styles: ['Crisp mineral whites (Loire, Chablis)', 'Elegant Pinot Noir (Burgundy)', 'Powerful Cabernet blends (Bordeaux)', 'Peppery Syrah (Rhône)', 'Aromatic Riesling (Alsace)', 'Juicy Gamay (Beaujolais)'],
    appellations: ['Burgundy', 'Bordeaux', 'Champagne', 'Loire Valley', 'Rhône Valley', 'Alsace', 'Languedoc-Roussillon', 'Provence', 'Beaujolais', 'Jura'],
    funFact: 'France is the benchmark for almost every major wine style in the world. From Champagne to Chardonnay, Pinot Noir to Cabernet – the French originals set the standard every other country tries to match.',
    mapColor: '#e8d0a0',
    zoomCenter: [2.5, 46.5],
    zoomScale: 4,
    subRegions: [
      { name: 'Loire Valley', style: 'Fresh & Mineral', grapes: 'Sauvignon Blanc, Chenin Blanc, Cabernet Franc', appellations: 'Sancerre, Vouvray, Muscadet, Pouilly-Fumé, Saumur-Champigny' },
      { name: 'Burgundy', style: 'Elegant & Precise', grapes: 'Chardonnay, Pinot Noir, Aligoté', appellations: 'Chablis, Gevrey-Chambertin, Meursault, Puligny-Montrachet, Nuits-Saint-Georges' },
      { name: 'Bordeaux', style: 'Classic & Structured', grapes: 'Cabernet Sauvignon, Merlot, Cabernet Franc', appellations: 'Médoc, Saint-Émilion, Pomerol, Margaux, Saint-Julien, Pomerol' },
      { name: 'Rhône Valley', style: 'Savoury & Spiced', grapes: 'Grenache, Syrah, Mourvèdre, Viognier', appellations: 'Châteauneuf-du-Pape, Hermitage, Crozes-Hermitage, Côtes du Rhône' },
      { name: 'Alsace', style: 'Aromatic & Dry', grapes: 'Riesling, Gewurztraminer, Pinot Gris', appellations: 'Grand Cru vineyards including Schoenenbourg, Rangen, Brand' },
      { name: 'Beaujolais & Jura', style: 'Fresh & Unique', grapes: 'Gamay, Trousseau, Poulsard', appellations: 'Fleurie, Moulin-à-Vent, Morgon, Arbois' },
    ],
  },
  '380': {
    name: 'Italy',
    flag: '🇮🇹',
    iso3: 'ITA',
    climate: 'Diverse: warm Mediterranean in the south and Sicily; cooler continental in the north (Piedmont, Veneto, Alto Adige). The Alps and Apennines create varied microclimates across 20 regions.',
    keyGrapes: ['Sangiovese', 'Nebbiolo', 'Barbera', 'Corvina', 'Primitivo', 'Verdicchio', 'Pinot Grigio', 'Vermentino', 'Grillo', 'Cortese'],
    styles: ['Structured Nebbiolo (Barolo, Barbaresco)', 'Fresh, acidic Sangiovese (Chianti, Brunello)', 'Rich dried-fruit reds (Amarone)', 'Crisp northern whites (Gavi, Verdicchio)', 'Bold southern reds (Primitivo)'],
    appellations: ['Barolo', 'Barbaresco', 'Chianti Classico', 'Brunello di Montalcino', 'Amarone', 'Bolgheri', 'Soave', 'Gavi', 'Verdicchio'],
    funFact: 'Italy has more DOC/DOCG appellations than any other country – over 500 – and more indigenous grape varieties than France, Spain and Germany combined. Every region has its own unique identity.',
    mapColor: '#d4b8a0',
    zoomCenter: [12.5, 42.5],
    zoomScale: 4,
    subRegions: [
      { name: 'Piedmont', style: 'Structure & Tannin', grapes: 'Nebbiolo, Barbera, Dolcetto, Cortese', appellations: 'Barolo, Barbaresco, Langhe, Gavi, Barbera d\'Asti' },
      { name: 'Veneto', style: 'Light & Elegant', grapes: 'Corvina, Garganega, Pinot Grigio', appellations: 'Valpolicella, Amarone, Soave, Prosecco' },
      { name: 'Tuscany', style: 'Balanced & Classic', grapes: 'Sangiovese, Cabernet Sauvignon (Bolgheri)', appellations: 'Chianti Classico, Brunello di Montalcino, Bolgheri, Morellino' },
      { name: 'Marche', style: 'Fresh & Mineral', grapes: 'Verdicchio, Pecorino, Passerina, Sangiovese', appellations: 'Verdicchio dei Castelli di Jesi, Falerio' },
      { name: 'Southern Italy', style: 'Ripe & Bold', grapes: 'Primitivo, Negroamaro, Greco, Grillo', appellations: 'Primitivo di Manduria, Gioia del Colle, Etna (Sicily)' },
    ],
  },
  '724': {
    name: 'Spain',
    flag: '🇪🇸',
    iso3: 'ESP',
    climate: 'Predominantly dry and warm; Atlantic influence in the northwest (Galicia, Rías Baixas); continental inland (Rioja, Ribera del Duero); hot and arid in the south. High altitude vineyards offset heat.',
    keyGrapes: ['Tempranillo', 'Garnacha', 'Mencía', 'Verdejo', 'Albariño', 'Monastrell', 'Cava grapes (Macabeo, Xarel-lo, Parellada)'],
    styles: ['Oak-aged Tempranillo (Rioja Reserva/Gran Reserva)', 'Fresh Atlantic whites (Albariño, Verdejo)', 'Structured reds (Ribera del Duero)', 'Light coastal reds (Mencía)', 'Bold Mediterranean blends (Priorat)'],
    appellations: ['Rioja', 'Ribera del Duero', 'Rías Baixas', 'Priorat', 'Rueda', 'Navarra', 'Bierzo', 'Cava', 'Jerez (Sherry)'],
    funFact: 'Spain has more land under vine than any other country in the world, yet produces less wine than France or Italy because much of the land is arid with low-yielding old vines. This concentration of fruit gives Spanish wines their intensity.',
    mapColor: '#e0c4a0',
    zoomCenter: [-3.5, 40],
    zoomScale: 3.5,
    subRegions: [
      { name: 'Rioja & Navarra', style: 'Oak & Elegance', grapes: 'Tempranillo, Garnacha, Graciano', appellations: 'Rioja Alta, Rioja Alavesa, Rioja Baja' },
      { name: 'Galicia (Rías Baixas)', style: 'Atlantic Freshness', grapes: 'Albariño, Mencía, Godello', appellations: 'Rías Baixas, Ribeira Sacra, Valdeorras' },
      { name: 'Castilla y León', style: 'Powerful & Pure', grapes: 'Tempranillo, Verdejo, Garnacha', appellations: 'Ribera del Duero, Rueda, Toro' },
    ],
  },
  '620': {
    name: 'Portugal',
    flag: '🇵🇹',
    iso3: 'PRT',
    climate: 'Atlantic influence in the west; continental interior (Douro, Dão, Alentejo). The Douro Valley is dramatic and hot with schist soils; the Vinho Verde region in the north is cool and rainy.',
    keyGrapes: ['Touriga Nacional', 'Touriga Franca', 'Tinta Roriz (Tempranillo)', 'Alvarinho', 'Loureiro', 'Arinto', 'Baga'],
    styles: ['Complex fortified wine (Port)', 'Fresh, slightly sparkling whites (Vinho Verde)', 'Structured red blends (Douro, Dão)', 'Rich southern reds (Alentejo)'],
    appellations: ['Douro', 'Vinho Verde', 'Dão', 'Alentejo', 'Bairrada', 'Setúbal', 'Madeira'],
    funFact: 'Portugal has over 250 indigenous grape varieties – more than most countries – and almost no international varieties planted. Every bottle is a window into unique local terroir. Port wine has been produced in the Douro Valley since the 1600s.',
    mapColor: '#d8c4a8',
    zoomCenter: [-8, 39.5],
    zoomScale: 5,
    subRegions: [
      { name: 'Vinho Verde', style: 'Light & Fresh', grapes: 'Alvarinho, Loureiro, Arinto', appellations: 'Monção, Melgaço, Lima, Cávado' },
      { name: 'Douro Valley', style: 'Structured & Complex', grapes: 'Touriga Nacional, Touriga Franca, Tinta Barroca', appellations: 'Douro DOC (dry), Port (fortified)' },
      { name: 'Dão', style: 'Elegant & Fragrant', grapes: 'Touriga Nacional, Jaen, Encruzado', appellations: 'Dão DOC (red and white)' },
    ],
  },
  '276': {
    name: 'Germany',
    flag: '🇩🇪',
    iso3: 'DEU',
    climate: 'Cool continental, one of the coolest major wine regions in the world. Vineyards planted on south-facing slopes to maximise sunlight. Rhine and Mosel rivers moderate temperatures.',
    keyGrapes: ['Riesling', 'Spätburgunder (Pinot Noir)', 'Grauburgunder (Pinot Gris)', 'Müller-Thurgau', 'Silvaner'],
    styles: ['Bone-dry Riesling (Trocken)', 'Off-dry Riesling (Feinherb)', 'Sweet Riesling (Auslese, Beerenauslese)', 'Light Pinot Noir (Spätburgunder)', 'Sparkling Sekt'],
    appellations: ['Mosel', 'Rheingau', 'Rheinhessen', 'Pfalz', 'Nahe', 'Württemberg', 'Baden', 'Franken'],
    funFact: 'Germany\'s steepest vineyards exceed 70° of slope – the Mosel\'s famous Bremmer Calmont reaches 65°. Harvesting here is entirely by hand; tractors cannot navigate the terrain. The effort produces some of the world\'s most age-worthy white wines.',
    mapColor: '#d4d8c0',
    zoomCenter: [10.5, 51],
    zoomScale: 4,
    subRegions: [],
  },
  '40': {
    name: 'Austria',
    flag: '🇦🇹',
    iso3: 'AUT',
    climate: 'Continental with warm summers and cold winters. The Wachau along the Danube, Kamptal, and Kremstal produce the finest Grüner Veltliner and Riesling. Burgenland in the east is warmer, suited to red wines and botrytis.',
    keyGrapes: ['Grüner Veltliner', 'Riesling', 'Zweigelt', 'Blaufränkisch', 'Saint-Laurent'],
    styles: ['Peppery, dry Grüner Veltliner', 'Mineral Riesling (Wachau)', 'Light Zweigelt reds', 'Sweet botrytis wines (Ausbruch, TBA)'],
    appellations: ['Wachau', 'Kamptal', 'Kremstal', 'Grüner Veltliner (DAC)', 'Burgenland', 'Steiermark'],
    funFact: 'Austria introduced one of the world\'s most rigorous wine quality systems after a wine scandal in 1985. Today Austrian wine is considered among the most reliably high-quality in the world, with very strict labelling and alcohol regulations.',
    mapColor: '#d0d4c0',
    zoomCenter: [14, 47.5],
    zoomScale: 5,
    subRegions: [],
  },
  '300': {
    name: 'Greece',
    flag: '🇬🇷',
    iso3: 'GRC',
    climate: 'Predominantly Mediterranean with hot, dry summers and mild winters. Higher altitude regions (Macedonia, Thessaly) are cooler and produce more structured wines. Over 300 days of sunshine per year.',
    keyGrapes: ['Assyrtiko', 'Xinomavro', 'Agiorgitiko', 'Moschofilero', 'Roditis', 'Malagousia'],
    styles: ['Mineral whites (Assyrtiko from Santorini)', 'Structured, tannic reds (Xinomavro from Naoussa)', 'Aromatic whites (Moschofilero)', 'Fortified sweet wines (Muscat of Samos)'],
    appellations: ['Naoussa (Xinomavro)', 'Santorini (Assyrtiko)', 'Nemea (Agiorgitiko)', 'Mantinia', 'Côtes de Meliton'],
    funFact: 'Greece has over 300 indigenous grape varieties, most of which are found nowhere else in the world. Viticulture here dates back over 4,000 years – some of the oldest evidence of winemaking anywhere on earth. Xinomavro literally means "acid black".',
    mapColor: '#d8d0b8',
    zoomCenter: [22, 38.5],
    zoomScale: 5,
    subRegions: [],
  },
  '840': {
    name: 'USA',
    flag: '🇺🇸',
    iso3: 'USA',
    climate: 'Enormously varied: California ranges from the cool, foggy Sonoma Coast and Russian River Valley to the hot Napa Valley floor. Oregon\'s Willamette Valley is cool and wet, closer to Burgundy in character.',
    keyGrapes: ['Cabernet Sauvignon (Napa)', 'Chardonnay', 'Pinot Noir (Oregon, Sonoma)', 'Zinfandel', 'Merlot', 'Syrah'],
    styles: ['Powerful Cabernet Sauvignon (Napa Valley)', 'Elegant Pinot Noir (Willamette Valley, Sonoma Coast)', 'Buttery Chardonnay (California)', 'Bold Zinfandel'],
    appellations: ['Napa Valley', 'Sonoma Coast', 'Russian River Valley', 'Willamette Valley (Oregon)', 'Santa Barbara County', 'Paso Robles'],
    funFact: 'At the 1976 "Judgement of Paris" blind tasting, California wines beat France\'s finest in both red and white categories – an event that shocked the wine world and put New World wines on the map. The tasting was organised by British wine merchant Steven Spurrier.',
    mapColor: '#e0d4b8',
    zoomCenter: [-100, 40],
    zoomScale: 1.5,
    subRegions: [
      { name: 'Napa Valley, California', style: 'Bold & Powerful', grapes: 'Cabernet Sauvignon, Merlot, Chardonnay', appellations: 'Oakville, Rutherford, Stags Leap, Howell Mountain' },
      { name: 'Sonoma County, California', style: 'Elegant & Diverse', grapes: 'Pinot Noir, Chardonnay, Zinfandel, Syrah', appellations: 'Sonoma Coast, Russian River Valley, Dry Creek Valley' },
      { name: 'Willamette Valley, Oregon', style: 'Burgundian Elegance', grapes: 'Pinot Noir, Chardonnay, Pinot Gris', appellations: 'Dundee Hills, Chehalem Mountains, Eola-Amity Hills' },
      { name: 'Santa Barbara County, California', style: 'Cool-Climate Finesse', grapes: 'Pinot Noir, Chardonnay, Syrah', appellations: 'Santa Maria Valley, Sta. Rita Hills' },
    ],
  },
  '32': {
    name: 'Argentina',
    flag: '🇦🇷',
    iso3: 'ARG',
    climate: 'Dry, sunny, high-altitude desert with dramatic temperature swings between day and night. Mendoza at 700-1200m elevation; Salta\'s Calchaquí Valleys reach 3,000m – some of the highest vineyards in the world.',
    keyGrapes: ['Malbec', 'Torrontés', 'Cabernet Sauvignon', 'Bonarda', 'Chardonnay'],
    styles: ['Rich, velvety Malbec', 'Aromatic Torrontés white', 'Full-bodied Cabernet blends', 'High-altitude elegant reds (Luján de Cuyo)'],
    appellations: ['Mendoza', 'Luján de Cuyo', 'Maipú', 'Uco Valley', 'Salta (Cafayate)'],
    funFact: 'Malbec was originally from Cahors in southwest France, where it is known as Côt or Auxerrois. Brought to Argentina in the 19th century, it thrived in Mendoza\'s high-altitude sunshine and became the country\'s signature grape. French Malbec is earthier; Argentine Malbec is more opulent and fruity.',
    mapColor: '#d8e0c4',
    zoomCenter: [-65, -35],
    zoomScale: 2.5,
    subRegions: [],
  },
  '152': {
    name: 'Chile',
    flag: '🇨🇱',
    iso3: 'CHL',
    climate: 'Long, narrow country with enormous climatic diversity. Cool coastal influence from the Pacific (Casablanca, San Antonio); warmer inland valleys (Maipo, Colchagua). The Atacama Desert in the north and Patagonia in the south create a 4,000km range.',
    keyGrapes: ['Cabernet Sauvignon', 'Carménère', 'Merlot', 'Sauvignon Blanc', 'Chardonnay', 'Pinot Noir'],
    styles: ['Structured Cabernet Sauvignon (Maipo)', 'Herbaceous Carménère', 'Fresh Sauvignon Blanc (Casablanca)', 'Elegant Pinot Noir (Bío Bío)'],
    appellations: ['Maipo Valley', 'Colchagua Valley', 'Casablanca Valley', 'San Antonio Valley', 'Leyda'],
    funFact: 'Carménère was thought to be extinct in Europe after the phylloxera louse wiped out vineyards in the 1860s, but was discovered thriving in Chile in 1994 – where it had been mistaken for Merlot for 130 years. It is now Chile\'s signature grape.',
    mapColor: '#d0dcc4',
    zoomCenter: [-71, -35],
    zoomScale: 2.5,
    subRegions: [],
  },
  '710': {
    name: 'South Africa',
    flag: '🇿🇦',
    iso3: 'ZAF',
    climate: 'Mediterranean in the Western Cape with hot, dry summers cooled by ocean breezes from both the Atlantic and Indian Oceans. The Swartland is warm and dry; Elgin and Walker Bay are cool and Atlantic-influenced.',
    keyGrapes: ['Chenin Blanc (Steen)', 'Pinotage', 'Cabernet Sauvignon', 'Shiraz', 'Sauvignon Blanc', 'Grenache'],
    styles: ['Old-vine Chenin Blanc (Swartland)', 'Pioneering natural wines', 'Powerful Cabernet (Stellenbosch)', 'Unique Pinotage'],
    appellations: ['Stellenbosch', 'Swartland', 'Paarl', 'Franschhoek', 'Elgin', 'Walker Bay', 'Constantia'],
    funFact: 'South Africa has more hectares of old-vine Chenin Blanc than the Loire Valley in France – its original home. Many of these bush vines are over 60 years old and were planted before the wine industry was established. The Swartland region, once dismissed as a bulk wine area, is now home to some of the world\'s most exciting natural winemakers.',
    mapColor: '#d4c8a8',
    zoomCenter: [25, -29],
    zoomScale: 3,
    subRegions: [],
  },
  '36': {
    name: 'Australia',
    flag: '🇦🇺',
    iso3: 'AUS',
    climate: 'Hugely varied: Mediterranean to cool maritime. Barossa Valley is warm and sunny (big Shiraz); Clare Valley is cooler with limestone soils (elegant Riesling); Adelaide Hills is cool altitude (Chardonnay, Pinot Noir); Margaret River is influenced by two oceans (Cabernet).',
    keyGrapes: ['Shiraz/Syrah', 'Cabernet Sauvignon', 'Chardonnay', 'Pinot Noir', 'Grenache', 'Riesling'],
    styles: ['Full-bodied Shiraz (Barossa, McLaren Vale)', 'Elegant cool-climate Chardonnay (Adelaide Hills)', 'Structured Cabernet Sauvignon (Margaret River)', 'Delicate Pinot Noir (Yarra Valley)', 'Dry Riesling (Clare Valley)'],
    appellations: ['Barossa Valley', 'Eden Valley', 'Clare Valley', 'Adelaide Hills', 'McLaren Vale', 'Margaret River', 'Yarra Valley', 'Beechworth', 'Coonawarra'],
    funFact: 'Australia\'s Penfolds Grange, made from Shiraz, is considered one of the world\'s greatest red wines – regularly fetching over £500 a bottle. Yet until the 1950s, Australian wine was mostly fortified. The transformation to fine table wine in a generation is one of the greatest stories in wine.',
    mapColor: '#e8d8b0',
    zoomCenter: [135, -27],
    zoomScale: 1.5,
    subRegions: [],
  },
  '554': {
    name: 'New Zealand',
    flag: '🇳🇿',
    iso3: 'NZL',
    climate: 'Cool maritime climate, especially in the South Island. Marlborough in the north of the South Island is dry and sunny with cool nights – ideal for Sauvignon Blanc. Central Otago is the world\'s southernmost wine region, known for Pinot Noir.',
    keyGrapes: ['Sauvignon Blanc', 'Pinot Noir', 'Chardonnay', 'Pinot Gris', 'Riesling'],
    styles: ['Intensely aromatic Sauvignon Blanc (Marlborough)', 'Elegant Pinot Noir (Central Otago, Martinborough)', 'Structured Chardonnay (Hawke\'s Bay)'],
    appellations: ['Marlborough', 'Central Otago', 'Hawke\'s Bay', 'Martinborough', 'Gisborne', 'Nelson'],
    funFact: 'New Zealand Sauvignon Blanc changed the world. When Cloudy Bay released its 1985 vintage, it showed an entirely new style – intensely tropical and aromatic – that became a global phenomenon. Marlborough now produces over 80% of all New Zealand wine.',
    mapColor: '#c8d8c4',
    zoomCenter: [172, -41],
    zoomScale: 4,
    subRegions: [],
  },
}

export const REGION_STYLES = {
  'Loire Valley': 'Fresh & Mineral',
  'Burgundy': 'Elegant & Subtle',
  'Bordeaux': 'Classic & Structured',
  'Southern France': 'Warm & Mediterranean',
  'Rest of France': 'Alsace, Jura & Beaujolais',
  'Rhône Valley': 'Savoury & Spiced',
  'Germany': 'Precise & Fresh',
  'Austria': 'Precise & Fresh',
  'Rioja': 'Savoury & Refined',
  'Spain & Portugal': 'Atlantic Freshness',
  'Northern Italy': 'Structure & Elegance',
  'Central Italy': 'Balanced & Classic',
  'Southern Italy': 'Ripe & Bold',
  'Greece': 'Ancient & Fresh',
  'New World': 'Bright & Fruitful',
  'Australia': 'Bold & Generous',
  'USA': 'Polished & Expressive',
}

// Map from country name to ISO numeric code (for highlighting)
export const COUNTRY_ISO_MAP = {
  'France': '250',
  'Italy': '380',
  'Spain': '724',
  'Portugal': '620',
  'Germany': '276',
  'Austria': '40',
  'Greece': '300',
  'USA': '840',
  'Argentina': '32',
  'Chile': '152',
  'South Africa': '710',
  'Australia': '36',
  'New Zealand': '554',
}

export const WINE_PRODUCING_ISOS = new Set(Object.keys(WINE_COUNTRIES))
